### ISSUE TITLE
Training

### ISSUE THREAD

**Issue by Adonis-Lbc** [egorchistov/color-transfer#1]
Thank you for your work. 
During the training process, I always prompted the following error when parsing yaml files。

usage: trainer.py [options] fit [-h] [-c CONFIG] [--print_config[=flags]]
                                [--seed_everything SEED_EVERYTHING]
                                [--trainer CONFIG]
                                [--trainer.accelerator.help CLASS_PATH_OR_NAME]
                                [--trainer.accelerator ACCELERATOR]
                                [--trainer.strategy.help CLASS_PATH_OR_NAME]
                                [--trainer.strategy STRATEGY]
                                [--trainer.devices DEVICES]
                                [--trainer.num_nodes NUM_NODES]
                                [--trainer.precision PRECISION]
                                [--trainer.logger.help CLASS_PATH_OR_NAME]
                                [--trainer.logger LOGGER]
                                [--trainer.callbacks.help CLASS_PATH_OR_NAME]
                                [--trainer.callbacks CALLBACKS]
                                [--trainer.fast_dev_run FAST_DEV_RUN]
                                [--trainer.max_epochs MAX_EPOCHS]
                                [--trainer.min_epochs MIN_EPOCHS]
                                [--trainer.max_steps MAX_STEPS]
                                [--trainer.min_steps MIN_STEPS]
                                [--trainer.max_time MAX_TIME]
                                [--trainer.limit_train_batches LIMIT_TRAIN_BATCHES]
                                [--trainer.limit_val_batches LIMIT_VAL_BATCHES]
                                [--trainer.limit_test_batches LIMIT_TEST_BATCHES]
                                [--trainer.limit_predict_batches LIMIT_PREDICT_BATCHES]
                                [--trainer.overfit_batches OVERFIT_BATCHES]
                                [--trainer.val_check_interval VAL_CHECK_INTERVAL]
                                [--trainer.check_val_every_n_epoch CHECK_VAL_EVERY_N_EPOCH]
                                [--trainer.num_sanity_val_steps NUM_SANITY_VAL_STEPS]
                                [--trainer.log_every_n_steps LOG_EVERY_N_STEPS]
                                [--trainer.enable_checkpointing {true,false,null}]
                                [--trainer.enable_progress_bar {true,false,null}]
                                [--trainer.enable_model_summary {true,false,null}]
                                [--trainer.accumulate_grad_batches ACCUMULATE_GRAD_BATCHES]
                                [--trainer.gradient_clip_val GRADIENT_CLIP_VAL]
                                [--trainer.gradient_clip_algorithm GRADIENT_CLIP_ALGORITHM]
                                [--trainer.deterministic DETERMINISTIC]
                                [--trainer.benchmark {true,false,null}]
                                [--trainer.inference_mode {true,false}]
                                [--trainer.use_distributed_sampler {true,false}]
                                [--trainer.profiler.help CLASS_PATH_OR_NAME]
                                [--trainer.profiler PROFILER]
                                [--trainer.detect_anomaly {true,false}]
                                [--trainer.barebones {true,false}]
                                [--trainer.plugins.help CLASS_PATH_OR_NAME]
                                [--trainer.plugins PLUGINS]
                                [--trainer.sync_batchnorm {true,false}]
                                [--trainer.reload_dataloaders_every_n_epochs RELOAD_DATALOADERS_EVERY_N_EPOCHS]
                                [--trainer.default_root_dir DEFAULT_ROOT_DIR]
                                [--model.help CLASS_PATH_OR_NAME]
                                --model CONFIG | CLASS_PATH_OR_NAME | .INIT_ARG_NAME VALUE
                                [--data.help CLASS_PATH_OR_NAME]
                                [--data CONFIG | CLASS_PATH_OR_NAME | .INIT_ARG_NAME VALUE]
                                [--optimizer.help CLASS_PATH_OR_NAME]
                                [--optimizer CONFIG | CLASS_PATH_OR_NAME | .INIT_ARG_NAME VALUE]
                                [--lr_scheduler.help CLASS_PATH_OR_NAME]
                                [--lr_scheduler CONFIG | CLASS_PATH_OR_NAME | .INIT_ARG_NAME VALUE]
                                [--ckpt_path CKPT_PATH]
trainer.py [options] fit: error: Parser key "model":
  'type' object is not subscriptable

- Can you help me? Thank you

**Comment by egorchistov** [comment]
Hi, thank you for your interest in our work!

What is your Python version? Seems like these errors [can appear in Python < 3.9](https://stackoverflow.com/questions/63460126/typeerror-type-object-is-not-subscriptable-in-a-function-signature), because I used new type annotations syntax, e.g. `list[int]` instead of `typing.List[int]`.

Could you please check if adding `from __future__ import annotations` line as the first import statement into `data.py`, `methods/modules.py` and `methods/simp.py` modules will solve the problem? If it so, I will add those fixes to the code.

**Comment by egorchistov** [comment]
I have tested the problem with Python 3.8. After adding `from __future__ import annotations` to the files, I get [Configuration check failed :: No action for destination key to check its value](https://github.com/Lightning-AI/lightning/issues/10859). I removed all type annotations for configurable-from-yaml classes, and now it works as expected. 

I'm closing the issue, but if you have any questions, feel free to reopen it.
